### PR TITLE
Wordselect breaks if Moodle option 'forceclean' is turned on (e.g. View as Student)

### LINKED ISSUE #22: Wordselect breaks if Moodle option 'forceclean' is turned on (e.g. View as Student)
Hi @marcusgreen,

I found an issue related to this question type as below:

The WordSelect will be break if Moodle option 'forceclean' is turned on. Now, it's only the experimental setting, but in the future, Moodle is going to turn it on by default.
See: https://tracker.moodle.org/browse/MDL-62352

Also, if you use the Moodle Log in as feature, the option will be forced on.
See: https://tracker.moodle.org/browse/MDL-63786

So, if we use Log in as feature, or we turn that option on in the Admin setting, WordSelect will be broken.

Thanks,

### PR DESCRIPTION
**Pull request by HuongNV13**
This will resolve #22

### CODE REVIEW

File: renderer.php [hunk 1]
```diff
@@ -43,21 +43,28 @@ class qtype_wordselect_renderer extends qtype_with_combined_feedback_renderer {
      */
     public function formulation_and_controls(question_attempt $qa, question_display_options $options) {
         global $PAGE;
+
+        $output = '';
```
Comment (marcusgreen) [inline renderer.php]: Should have had that in anyway....

**Comment by HuongNV13** [comment]
Hi @marcusgreen,

Could you please take a look at this?

Thanks,

**Comment by marcusgreen** [comment]
I will investigate the travis errors, probably this weekend.
